-- 1. CRIAÇÃO DAS TABELAS
CREATE TABLE CLIENTES (
    ID_CLIENTE SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100),
    TELEFONE VARCHAR(20)
);

CREATE TABLE FATURAS (
    ID_FATURA SERIAL PRIMARY KEY,
    ID_CLIENTE INT REFERENCES CLIENTES(ID_CLIENTE),
    VALOR_FATURA DECIMAL(10, 2) NOT NULL,
    VALOR_PAGO DECIMAL(10, 2), -- Pode ser NULL se não pagou
    DATA_VENCIMENTO DATE NOT NULL,
    DATA_PAGAMENTO DATE -- Pode ser NULL se estiver em aberto
);

-- 2. INSERÇÃO DE DADOS DE TESTE (com casos de NULL e atrasos)
INSERT INTO CLIENTES (NOME, EMAIL, TELEFONE) VALUES
('CARLOS SILVA', 'carlos@email.com', '31999991111'),
('MARIANA ROCHA', NULL, '31999992222'), -- Email NULL
('FERNANDO SOUZA', 'fernando@email.com', NULL), -- Telefone NULL
('PATRICIA LIMA', NULL, NULL); -- Email e Telefone NULL

INSERT INTO FATURAS (ID_CLIENTE, VALOR_FATURA, VALOR_PAGO, DATA_VENCIMENTO, DATA_PAGAMENTO) VALUES
(1, 1500.00, 1500.00, '2024-05-10', '2024-05-08'), -- Pagou em dia
(1, 2000.00, NULL,    '2024-06-10', NULL),         -- Em aberto
(2, 850.00,  850.00,  '2024-05-15', '2024-05-20'), -- Pagou com atraso
(2, 1200.00, NULL,    '2024-01-10', NULL),         -- Em aberto muito atrasado
(3, 3000.00, 1500.00, '2024-05-01', '2024-05-01'), -- Pagamento parcial
(4, 500.00,  NULL,    '2024-06-01', NULL);         -- Em aberto recente

-- VISUALIZANDO AS TABELAS
SELECT * FROM CLIENTES;
SELECT * FROM FATURAS;

-- CONTATO PRINCIPAL COM O CLIENTE + TRATAMENTO DE NULOS
SELECT
	NOME,
	EMAIL,
	TELEFONE,
	COALESCE(EMAIL, TELEFONE, 'SEM CONTATO CADASTRADO') AS CANAL_CONTATO
FROM CLIENTES;

-- DATA EFETIVA DE QUITAÇÃO E DIAS DE ATRASOS
SELECT
	ID_FATURA,
	VALOR_FATURA,
	DATA_VENCIMENTO,
	DATA_PAGAMENTO,
	COALESCE(DATA_PAGAMENTO, '2024-06-15') AS DATA_FINAL,
	CASE
		WHEN DATA_PAGAMENTO IS NULL THEN 'EM ABERTO'
		WHEN DATA_PAGAMENTO <= DATA_VENCIMENTO THEN 'PAGO EM DIA'
		ELSE 'PAGAMENTO ATRASADO'
	END AS STATUS_PAGAMENTO
FROM FATURAS;

-- CALCULO DE SALDO E RISCO FINANCEIRO
SELECT 
	ID_FATURA,
	VALOR_FATURA,
	COALESCE(VALOR_PAGO, 0.00) AS VALOR_RECEBIDO,
	CASE
		WHEN VALOR_PAGO >= VALOR_FATURA THEN 'QUITADO'
		WHEN VALOR_PAGO < VALOR_FATURA THEN 'PAGAMENTO_PARCIAL'
		ELSE 'PENDENTE_TOTAL'
	END AS STATUS_SALDO
FROM FATURAS;

-- VOLUMETRIA DE FATURAS POR CLIENTE
SELECT 
	F.ID_CLIENTE,
	C.NOME,
	COUNT(F.ID_FATURA) AS TOTAL_FATURAS,
	COUNT(
		CASE
			WHEN F.DATA_PAGAMENTO IS NOT NULL THEN 1
		END
	) AS FATURAS_PAGAS,
	COUNT(
		CASE
			WHEN F.DATA_PAGAMENTO IS NULL THEN 1
		END
	)  AS FATURAS_EM_ABERTO
FROM FATURAS F
INNER JOIN CLIENTES C
ON F.ID_CLIENTE = C.ID_CLIENTE
GROUP BY F.ID_CLIENTE, C.NOME;

-- RESUMO FINANCEIRO DE COBRANÇA
SELECT
	F.ID_CLIENTE, C.NOME,
	SUM(F.VALOR_FATURA) AS TOTAL_EMITIDO,
	SUM(COALESCE(F.VALOR_PAGO, 0.00)) AS TOTAL_ARRECADADO,
	COALESCE(SUM(
		CASE
			WHEN F.DATA_PAGAMENTO IS NULL THEN F.VALOR_FATURA
			ELSE 0
			END
	), 0.00) AS TOTAL_PENDENTE
FROM FATURAS F
INNER JOIN CLIENTES C
ON F.ID_CLIENTE = C.ID_CLIENTE
GROUP BY F.ID_CLIENTE, C.NOME;

-- ARRECADAÇÃO POR FORMA DE QUITAÇÃO
SELECT
	F.ID_CLIENTE, 
	C.NOME,
	COALESCE(SUM(
		CASE
			WHEN F.DATA_PAGAMENTO <= F.DATA_VENCIMENTO THEN VALOR_PAGO
			ELSE 0
			END
	), 0.00) AS TOTAL_PAGO_EM_DIA,
	COALESCE(SUM(
		CASE
			WHEN F.DATA_PAGAMENTO > F.DATA_VENCIMENTO THEN VALOR_PAGO
			ELSE 0
			END
	), 0.00) AS TOTAL_PAGO_COM_ATRASO
FROM FATURAS F
INNER JOIN CLIENTES C
ON F.ID_CLIENTE = C.ID_CLIENTE
GROUP BY F.ID_CLIENTE, C.NOME;
